# HW

In [2]:
import numpy as np
import pandas as pd

##### Загрузите датасет titanic.csv

In [3]:
df_titanic = pd.read_csv('titanic.csv')

In [4]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df_titanic.shape

(891, 12)

In [6]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


> Обратите внимание на разное количество значений переменных
Если это так - то у вас пропуски в данных. Такое бывает. 
Например в этом датасете не получилось выяснить всех подробностей у некоторых людей в виду утери данных, невозможности узнать или восстановить их

In [7]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

> Давайте возьмем для начала только несколько признаков, позже - вы увеличите их количество и сделаете соответствующую обработку.

In [8]:
columns = ['Sex', 'Age', 'Pclass', 'Survived']

In [9]:
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:]

print(simple_train)


        Sex   Age  Pclass  Survived
0      male  22.0       3         0
1    female  38.0       1         1
2    female  26.0       3         1
3    female  35.0       1         1
4      male  35.0       3         0
5      male   NaN       3         0
6      male  54.0       1         0
7      male   2.0       3         0
8    female  27.0       3         1
9    female  14.0       2         1
10   female   4.0       3         1
11   female  58.0       1         1
12     male  20.0       3         0
13     male  39.0       3         0
14   female  14.0       3         0
15   female  55.0       2         1
16     male   2.0       3         0
17     male   NaN       2         1
18   female  31.0       3         0
19   female   NaN       3         1
20     male  35.0       2         0
21     male  34.0       2         1
22   female  15.0       3         1
23     male  28.0       1         1
24   female   8.0       3         0
25   female  38.0       3         1
26     male   NaN       3   

> мы пока не умеем на уровне алгоритма работать с пропущенными значениями. 
Представьте вам дают 5-мерный вектор у которого заполнены только три компоненты и другой такой же вектор но у него заполнены лишь две  компоненты.  Как померить их сходство????

distance_between( [1,0,1, NaN, NaN], [NaN, 1, 1, NaN, NaN] )


> один из вариантов - заполнить какими то значениями - например если это возраст - то заполнить средним по датасету или нулем.

>> на будущее - в sklearn есть такой модуль - http://scikit-learn.org/stable/modules/impute.html но сейчас можете заполнить пропуски средствами pandas - метод fillna()

##### Заполните пропущенные значения чем нибудь

In [10]:
simple_train['Age'].sum()
simple_train['Age'].idxmin()
simple_train['Age'].idxmax()
simple_train['Age'].min()
simple_train['Age'].max()
simple_train.agg(['sum', 'mean'])
simple_train['Age'].fillna(simple_train['Age'].mean())
#print(frame.sum())
#print(frame.mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.174185
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.174185
18     31.000000
19     29.174185
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.174185
27     19.000000
28     29.174185
29     29.174185
         ...    
471    38.000000
472    33.000000
473    23.000000
474    22.000000
475    29.174185
476    34.000000
477    29.000000
478    22.000000
479     2.000000
480     9.000000
481    29.174185
482    50.000000
483    63.000000
484    25.000000
485    29.174185
486    35.000000
487    58.000000
488    30.000000
489     9.000000
490    29.174185
491    21.000000
492    55.000000
493    71.000000
494    21.000000
495    29.174185
496    54.000000
497    29.174185
498    25.0000

In [11]:
simple_train['Age'] = simple_train['Age'].fillna(simple_train['Age'].mean())
simple_test['Age'] = simple_test['Age'].fillna(simple_test['Age'].mean())
# можно inplace делать такое, а можно переприсваивать.

> мы чемпионы. Но мы понимаем, что алгоритм у нас метрический - он не понимает как померить близость векторов в которых содержатся строки

distance( [1,1,0,'мужик'], [1, 0, 1, 'принцесска'] )

> поэтому давайте заведем признак is_man который будет принимать значение 0 или 1.

##### Заведите бинарный признак отвечающий за пол. Строковый удалите

хинт - есть метод apply()

In [12]:
simple_train.Sex = simple_train.Sex.replace(to_replace = dict(female = 0, male = 1))
simple_test.Sex = simple_test.Sex.replace(to_replace = dict(female = 0, male = 1))
print(simple_train)
print(simple_test)

     Sex        Age  Pclass  Survived
0      1  22.000000       3         0
1      0  38.000000       1         1
2      0  26.000000       3         1
3      0  35.000000       1         1
4      1  35.000000       3         0
5      1  29.174185       3         0
6      1  54.000000       1         0
7      1   2.000000       3         0
8      0  27.000000       3         1
9      0  14.000000       2         1
10     0   4.000000       3         1
11     0  58.000000       1         1
12     1  20.000000       3         0
13     1  39.000000       3         0
14     0  14.000000       3         0
15     0  55.000000       2         1
16     1   2.000000       3         0
17     1  29.174185       2         1
18     0  31.000000       3         0
19     0  29.174185       3         1
20     1  35.000000       2         0
21     1  34.000000       2         1
22     0  15.000000       3         1
23     1  28.000000       1         1
24     0   8.000000       3         0
25     0  38

##### Сформируйте трейн и тест выборку, где в X лежат признаки 'Sex', 'Age', 'Pclass', а в у - Survived

Результат - numpy array

hint - у pandas есть метод drop() и атрибут values; Пощупайте их

In [20]:
X_train = simple_train.drop(columns = ['Survived']).values
X_test = simple_test.drop(columns = ['Survived']).values
y_train = simple_train['Survived'].values
y_test = simple_test['Survived'].values
X_train = (X_train - X_train.mean(axis = 0)) / X_train.std(axis = 0)
X_test = (X_test - X_test.mean(axis = 0)) / X_test.std(axis = 0)
print(X_test)

[[ 7.01688259e-01 -1.02813535e+00  8.43335318e-01]
 [-1.42513429e+00 -7.19426333e-01  8.43335318e-01]
 [-1.42513429e+00  2.74188685e-16  8.43335318e-01]
 ...
 [-1.42513429e+00  2.74188685e-16  8.43335318e-01]
 [ 7.01688259e-01 -3.33540064e-01 -1.52042174e+00]
 [ 7.01688259e-01  1.29523459e-01  8.43335318e-01]]


In [21]:
assert isinstance(X_train, np.ndarray)
assert isinstance(X_test, np.ndarray)
assert isinstance(y_train, np.ndarray)
assert isinstance(y_test, np.ndarray)

In [22]:
assert X_train.shape[0] == y_train.shape[0]
assert X_test.shape[0] == y_test.shape[0]

In [23]:
assert not np.any(np.isnan(X_train)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'
assert not np.any(np.isnan(X_test)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'

##### Реализуйте KNN. Сами, как делали это на лекции. 

Можете улучшить его.
(например использовать kd-tree для быстрого поиска ближайших соседей, 
 или обходить соседей и класть расстояния в мин-кучу - тогда вы быстрее будете набирать их, без сортировки.)

In [24]:
from scipy.spatial import distance
class KNN:
    """
    simple KNN classifier with O(n) complexity for memory,
    and O(n log n) complexity - for nn search.
    """
    
    def __init__(self, n):
        self.n = n
        
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X):
        y_hat = []
        assert len(X.shape) == 2
        for elem in X:
            counts=[0,0]
            o = []
            for i in range(len(self.X)):
                o.append(distance.euclidean(elem, self.X[i]))
            k = np.array(o).argsort()[:self.n]
            print(k)
            counts[1] = sum(self.y[k])
            counts[0] = self.n-counts[1]
            
            prediction = counts.index(max(counts))
            y_hat.append(prediction)
        return np.array(y_hat)    
                
            
            
        

In [25]:
knn = KNN(5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(y_pred)

[266  86 138 220 282]
[404 113 192  44 436]
[240 274  32 198 415]
[279  25  85  40  18]
[435 329 307 311 136]
[ 27 102 373  97 118]
[190 123 472 322  98]
[475  55 351 185  64]
[146 321 162  73 401]
[ 75 267 271 353 442]
[105 313 355 281 392]
[250 384  36 364 354]
[447 390 137 248 273]
[496 299 177  52 268]
[350 296   0 287 320]
[ 92 331 339  62 187]
[472 123 190 416  98]
[250 384  36 364 354]
[211 416  98 327 387]
[253 365 157 286 488]
[334  31 166 306 457]
[ 51 173 115  37 408]
[250 384  36 364 354]
[380 194 337 319   1]
[250 384  36 364 354]
[ 13 400 360 188 153]
[259 458 440  15 432]
[475  55 351 185  64]
[108 471 465 104 400]
[120  72 135 398 234]
[ 43  58 237 446   9]
[250 384  36 364 354]
[266  86 138 220 282]
[240 274  32 198 415]
[251 255 109  28 264]
[ 58 237  43 446   9]
[245  62 187 339 331]
[334  31 166 306 457]
[250 384  36 364 354]
[151 356 136 291  88]
[269 486 383 258 230]
[ 24 147 419 233 448]
[419 147  24  39  14]
[439 418 219 213 178]
[453 460 434 110 462]
[252 438 1

[199 316 437 345 247]
[ 74 429 382 206 130]
[436 106 402 404 113]
[221 342 134 343 117]
[210 294 499 127  89]
[ 25  40 279 254  85]
[343 134 221 234 342]
[311 307 291 136 329]
[240 274  32 198 415]
[370 484 139 118  97]
[253 365 157 286 488]
[0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 0
 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1
 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1
 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0
 0 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0
 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0
 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0
 0 1 0 0

##### посчитайте руками (не используя sklearn) качество вашего предсказания

In [26]:
acc = np.mean(y_pred == y_test)
print('доля правильных ответов:', acc)

доля правильных ответов: 0.8005115089514067


In [27]:
np.unique(y_pred)

array([0, 1])

> Мы получили бейслайн решение. Оно должно давать скорр в районе 0.76

____

In [28]:
### можете проверить себя

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8005115089514067


In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

np.unique(y_pred)

print(accuracy_score(y_test, y_pred))

0.8107416879795396


##### TODO продолжение домашки