In [1]:
import numpy as np
import pandas as pd

In [2]:
df_titanic = pd.read_csv('titanic.csv')

In [3]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_titanic.shape

(891, 12)

In [5]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [6]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
columns = ['Sex', 'Age', 'Pclass', 'Survived']
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:]
print(simple_train)
print(simple_test)

In [8]:
print(simple_train['Age'].sum())
print(simple_train['Age'].idxmin())
print(simple_train['Age'].idxmax())
print(simple_train['Age'].min())
print(simple_train['Age'].max())

11640.5
469
96
0.75
71.0


In [9]:
simple_test.iloc[3:5,0:2]

Sex   Age
503  female  37.0
504  female  16.0

In [13]:
type(simple_train.iat[1,1])

numpy.float64

In [14]:
type(simple_train.iloc[1,1])

numpy.float64

In [15]:
simple_test.is

SyntaxError: invalid syntax (<ipython-input-15-4bb16d32289e>, line 1)

In [24]:
df = pd.Series([5, 6, 7, 8 ])

In [25]:
df.mean()

6.5

In [33]:
simple_train.apply(lambda x : 1)

Sex         1
Age         1
Pclass      1
Survived    1
dtype: int64

In [47]:
print(simple_train)

     Sex   Age  Pclass  Survived
0      1  22.0       3         0
1      0  38.0       1         1
2      0  26.0       3         1
3      0  35.0       1         1
4      1  35.0       3         0
5      1   NaN       3         0
6      1  54.0       1         0
7      1   2.0       3         0
8      0  27.0       3         1
9      0  14.0       2         1
10     0   4.0       3         1
11     0  58.0       1         1
12     1  20.0       3         0
13     1  39.0       3         0
14     0  14.0       3         0
15     0  55.0       2         1
16     1   2.0       3         0
17     1   NaN       2         1
18     0  31.0       3         0
19     0   NaN       3         1
20     1  35.0       2         0
21     1  34.0       2         1
22     0  15.0       3         1
23     1  28.0       1         1
24     0   8.0       3         0
25     0  38.0       3         1
26     1   NaN       3         0
27     1  19.0       1         0
28     0   NaN       3         1
29     1  

In [66]:
simple_train.drop(['Sex', 'Age'], axis = 1 ).values

array([[3, 0],
       [1, 1],
       [3, 1],
       ...,
       [1, 0],
       [3, 0],
       [3, 0]], dtype=int64)

In [65]:
simple_train.rename(id, axis = 'index')

Sex   Age  Pclass  Survived
1460038688       1  22.0       3         0
1460038720       0  38.0       1         1
1460038752       0  26.0       3         1
1460038784       0  35.0       1         1
1460038816       1  35.0       3         0
1460038848       1   NaN       3         0
1460038880       1  54.0       1         0
1460038912       1   2.0       3         0
1460038944       0  27.0       3         1
1460038976       0  14.0       2         1
1460039008       0   4.0       3         1
1460039040       0  58.0       1         1
1460039072       1  20.0       3         0
1460039104       1  39.0       3         0
1460039136       0  14.0       3         0
1460039168       0  55.0       2         1
1460039200       1   2.0       3         0
1460039232       1   NaN       2         1
1460039264       0  31.0       3         0
1460039296       0   NaN       3         1
1460039328       1  35.0       2         0
1460039360       1  34.0       2         1
1460039392       0  15.0       3         1
1460039424       1  28.0       1         1
1460039456       0   8.0       3         0
1460039488       0  38.0       3         1
1460039520       1   NaN       3         0
1460039552       1  19.0       1         0
1460039584       0   NaN       3         1
1460039616       1   NaN       3         0
...            ...   ...     ...       ...
1907371590832    1  38.0       3         0
1907371590864    0  33.0       2         1
1907371590896    0  23.0       2         1
1907371590928    0  22.0       3         0
1907371590960    1   NaN       1         0
1907371590992    1  34.0       2         0
1907371591024    1  29.0       3         0
1907371591056    1  22.0       3         0
1907371591088    0   2.0       3         1
1907371591120    1   9.0       3         0
1907371591152    1   NaN       2         0
1907371591184    1  50.0       3         0
1907371591216    0  63.0       3         1
1907371591248    1  25.0       1         1
1907371591280    0   NaN       3         0
1907371591312    0  35.0       1         1
1907371591344    1  58.0       1         0
1907371591376    1  30.0       3         0
1907371591408    1   9.0       3         1
1907371591440    1   NaN       3         0
1907371591472    1  21.0       3         0
1907371591504    1  55.0       1         0
1907371591536    1  71.0       1         0
1907371591568    1  21.0       3         0
1907371591600    1   NaN       3         0
1907371591632    0  54.0       1         1
1907371591664    1   NaN       3         0
1907371591696    0  25.0       1         0
1907371591728    1  24.0       3         0
1907371591760    1  17.0       3         0

[501 rows x 4 columns]

In [73]:

X_train = simple_train.drop(['Survived'],axis=1).values
X_test = simple_test.drop(['Survived'],axis=1).values
y_train = simple_train['Survived'].values
y_test = simple_test['Survived'].values
mean_ = X_train.mean(axis = 0)
std_ = X_train.std(axis=0)

In [74]:
print(mean_)

[0.63073852        nan 2.32734531]


In [70]:
print(std_)

[0.48260485        nan 0.82659797]


In [75]:
print(X_train)

[[ 1. 22.  3.]
 [ 0. 38.  1.]
 [ 0. 26.  3.]
 ...
 [ 0. 25.  1.]
 [ 1. 24.  3.]
 [ 1. 17.  3.]]


In [78]:
simple_train.values


array([[ 1., 22.,  3.,  0.],
       [ 0., 38.,  1.,  1.],
       [ 0., 26.,  3.,  1.],
       ...,
       [ 0., 25.,  1.,  0.],
       [ 1., 24.,  3.,  0.],
       [ 1., 17.,  3.,  0.]])